### ISSUE TITLE
Issue after installing 1.1.0

### ISSUE THREAD

**Issue by richarth** [callumbwhyte/super-value-converters#9]
Hi,

I've just tried installing 1.1.0 and I received this [error](https://gist.github.com/richarth/5dfea5f16edf3d7063ea851b2a77cc5a).  Let me know if you need any other information.

Richard

**Comment by callumbwhyte** [comment]
Hello Richard,

Thanks again for your feedback - sorry you've still been having some issues...

I managed to track down the bug you were reporting and add some additional safety checks.

I would encourage you to install v1.2.0 (for Umbraco 7) or v2.0.0 (for Umbraco 8) in order to fix your issue!

Cheers,
Callum

**Comment by richarth** [comment]
Hi,

Thanks for the update.  I've installed v1.2 and I can confirm that works great.

Thanks again
Richard
